<!doctype html>
<html lang="en">
<head>

	<base href="/"/>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="./assets/painel/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>DOC CLOUD - PAINEL</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="../assets/painel/css/bootstrap.min.css" rel="stylesheet" />
    
    <!-- Animation library for notifications   -->
    <link href="./assets/painel/css/animate.min.css" rel="stylesheet"/>
    <!--  Light Bootstrap Table core CSS    -->
  	
    <link href="./assets/painel/css/light-bootstrap-dashboard.css" rel="stylesheet"/>
    
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../assets/painel/css/demo.css" rel="stylesheet" />
    <link href="../assets/painel/css/datepicker.css" rel="stylesheet" />

    <!-- Fonts and icons -->
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="./assets/painel/css/pe-icon-7-stroke.css" rel="stylesheet" />
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    
    <script src="./assets/painel/js/jquery.min.js" type="text/javascript"></script>
    <script src="./assets/painel/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="./assets/painel/js/bootstrap.min.js" type="text/javascript"></script>
    
    <script src="./assets/painel/js/ckeditor/ckeditor.js"></script>
    
	<script src="./assets/painel/js/moment.min.js"></script>
    <script src="./assets/painel/js/bootstrap-datetimepicker.js"></script>
    <script src="./assets/painel/js/bootstrap-selectpicker.js"></script>
	<script src="./assets/painel/js/bootstrap-checkbox-radio-switch-tags.js"></script>
    <script src="./assets/painel/js/bootstrap-notify.js"></script>
	<script src="./assets/painel/js/sweetalert2.js"></script>
    <script src="./assets/painel/js/jquery.bootstrap.wizard.min.js"></script>
    <script src="./assets/painel/js/fullcalendar.min.js"></script>
	<script src="./assets/painel/js/app.js"></script>
	<script src="./assets/painel/js/jquery.maskMoney.js"></script>
    
</head>
<body>
<style>
    .sidebar:after, .bootstrap-navbar:after{
        background: linear-gradient(to bottom, #004d9f 25%, #004d9f 100%) !important;
    }
    .btn{
        color:#fff ;
    }
</style>


<div class="wrapper">

	<div class="sidebar" data-color="white" data-image="">
        <div class="logo">
            <a href="/painelinstitucional/painel" class="logo-text">
                <img src="/assets/painel/img/logo-branco.png" />
            </a>
        </div>
		<div class="logo logo-mini">
			<a href="/painelinstitucional/painel" class="logo-text">
				DC
			</a>
		</div>

    	<div class="sidebar-wrapper">
            <div class="user " style="margin: 0; padding: 0;">
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" style="color: #fff;" class="collapsed">
                        <?php echo strtoupper($this->me->login);?>
                    </a>
                </div>
            </div>

            <ul class="nav">
                <li>
                    <a href="/<?php echo $this->layout()->routes['module']?>/index/index">
                        <i class="fa fa-home"></i>
                        <p>Home</p>
                    </a>
                </li>
                
                <?php echo $this->partial('/layout/menu/menu.phtml');?>
                
                
            </ul>
    	</div>
    </div>
    <div class="main-panel">
		
		<nav class="navbar navbar-default">
            <div class="container-fluid">
				<div class="navbar-minimize">
					<button id="minimizeSidebar" class="btn btn-warning btn-fill btn-round btn-icon">
						<i class="fa fa-ellipsis-v visible-on-sidebar-regular"></i>
						<i class="fa fa-navicon visible-on-sidebar-mini"></i>
					</button>
				</div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?php if($this->baseModule == 'painelinstitucional' && $this->baseController == 'painel' && $this->baseAction == 'index'):?>
                        <p class="navbar-brand" >Home</p>
                    <?php else:?> 
                    	<p class="navbar-brand" ><?php echo strtoupper($this->layout()->routes['controller']);?></p>
                    <?php endif; ?>
                </div>
                <div class="collapse navbar-collapse">


                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="/<?php echo $this->layout()->routes['module'];?>/login/logout">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                <p>Sair</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        
        
        
        
        
        <?php echo $this->content; ?>
        
        
        
        
                
        <footer class="footer">
            <div class="container-fluid">
                <p class="copyright pull-right" style="color: #978154;">
                    &copy; <script>document.write(new Date().getFullYear())</script></a>.
                </p>
            </div>
        </footer>

    </div>
</div>


</body>

	
	
		<!--  Forms Validations Plugin -->
	<script src="./assets/painel/js/jquery.validate.min.js"></script>

	<!--  Plugin for Date Time Picker and Full Calendar Plugin-->


    <!--  Date Time Picker Plugin is included in this js file -->
    <script src="/assets/painel/js/bootstrap-datetimepicker.js"></script>
    
    <!--  Date Time Picker Plugin is included in this js file -->
    <script src="/assets/painel/js/bootstrap-datepicker.js"></script>
	
    <!--  Select Picker Plugin -->
    <script src="/assets/painel/js/bootstrap-selectpicker.js"></script>
	
	<!--  Checkbox, Radio, Switch and Tags Input Plugins -->
	<script src="/assets/painel/js/bootstrap-checkbox-radio-switch-tags.js"></script>

	<!--  Charts Plugin -->
	<script src="/assets/painel/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="/assets/painel/js/bootstrap-notify.js"></script>
	
    <!-- Sweet Alert 2 plugin -->
	<script src="/assets/painel/js/sweetalert2.js"></script>

    <!-- Vector Map plugin -->
	<script src="/assets/painel/js/jquery-jvectormap.js"></script>

    <!--  Google Maps Plugin    
    <script src="https://maps.googleapis.com/maps/api/js"></script>
	-->
	<!-- Wizard Plugin    -->
    <script src="/assets/painel/js/jquery.bootstrap.wizard.min.js"></script>
	
	<!--  Bootstrap Table Plugin    -->
	<script src="/assets/painel/js/bootstrap-table.js"></script>

	<!--  Plugin for DataTables.net  -->
	<script src="/assets/painel/js/jquery.datatables.js"></script>

    <!--  Full Calendar Plugin    -->
    <script src="/assets/painel/js/fullcalendar.min.js"></script>

    <!-- Light Bootstrap Dashboard Core javascript and methods -->
	<script src="/assets/painel/js/light-bootstrap-dashboard.js"></script>
	
	<!--   Sharrre Library    -->
    <script src="/assets/painel/js/jquery.sharrre.js"></script>
	
    <!-- MESSAGES -->
	<?php echo $this->message(); ?>
	
	
    <script type="text/javascript">
    $().ready(function(){
        $('#allInputsFormValidation').validate();
        $( "#datepicker" ).datepicker();
 	 });
	</script>
	<?php /*?>
	<script src="./assets/painel/js/demo.js"></script>
     */?>
</html>