
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="/assets/painel/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>DOC CLOUD - PAINEL</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />



    <!-- Bootstrap core CSS     -->
    <link href="/assets/painel/css/bootstrap.min.css" rel="stylesheet" />

    <!--  Light Bootstrap Dashboard core CSS    -->
    <link href="/assets/painel/css/light-bootstrap-dashboard.css" rel="stylesheet"/>

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="/assets/painel/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="/assets/painel/css/pe-icon-7-stroke.css" rel="stylesheet" />
    <style type="text/css">
        .full-page:after{
            background: linear-gradient(to bottom, #004d9f 15%, #fff 100%);
        }
        .full-page[data-color="orange"]:after{
            background-color: #fff;
            background-size: cover;
            background-position: right bottom;
        }
        .btn-warning.btn-fill{
            background-color: rgba(255, 255, 255, 0.56) !IMPORTANT;
            color: #fff;
        }
        .btn-warning.btn-fill:hover{
            background-color: #004d9f;
            color: #fff;
        }
        .btn-warning{
            border-color: #004d9f !important;
        }
        .login-page .card {
            background-color: #fff !important;
        }
        .btn-login{
            background-color: #004d9f !important;
        }
        .btn-login:hover{
            color: #fff!important;
            border: 1px solid #fff;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="color:#fff !important;" href="javascript:;">DOC CLOUD - PAINEL</a>
        </div>
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">
            </ul>
        </div>
    </div>
</nav>


<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" data-color="white" data-image="">

        <!--   you can change the color of the filter page using: data-color="blue | azure | green | orange | red | purple" -->
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                        <form method="post" action="/painel/login/logar-admin">

                            <!--   if you want to have the card without animation please remove the ".card-hidden" class   -->
                            <div class="card ">
                                <div class="header text-center">
                                    <img src="/assets/painel/img/logo.png" alt="logotipo">
                                </div>
                                <div class="content">
                                    <div class="form-group">
                                        <label>LOGIN</label>
                                        <input type="text" name="lg" placeholder="Login" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>SENHA</label>
                                        <input type="password" name="pw" placeholder="Senha" class="form-control">
                                    </div>
                                </div>
                                <div class="footer text-center">
                                    <button type="submit" class=" bt btn btn-login">LOGIN</button>
                                </div>
                            </div>
                            <input type="hidden" name="method" value="logarAdmin" />
                        </form>

                    </div>
                </div>
            </div>
        </div>

        <footer class="footer footer-transparent">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">

                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right" style="color: #2aafe4;">
                    <a href="https://www.creative-tim.com" style="color: #2aafe4;">© 2020 DOCCLOUD.</a> Todos os direitos reservados.
                </p>
            </div>
        </footer>

    </div>

</div>

<!-- MESSAGES -->
<?php echo $this->message(); ?>

</body>

<!--   Core JS Files and PerfectScrollbar library inside jquery.ui   -->
<script src="/assets/painel/js/jquery.min.js" type="text/javascript"></script>
<script src="/assets/painel/js/jquery-ui.min.js" type="text/javascript"></script>
<script src="/assets/painel/js/bootstrap.min.js" type="text/javascript"></script>



<!--  Forms Validations Plugin -->
<script src="/assets/painel/js/jquery.validate.min.js"></script>

<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="/assets/painel/js/moment.min.js"></script>

<!--  Date Time Picker Plugin is included in this js file -->
<script src="/assets/painel/js/bootstrap-datetimepicker.js"></script>

<!--  Select Picker Plugin -->
<script src="/assets/painel/js/bootstrap-selectpicker.js"></script>

<!--  Checkbox, Radio, Switch and Tags Input Plugins -->
<script src="/assets/painel/js/bootstrap-checkbox-radio-switch-tags.js"></script>

<!--  Charts Plugin -->
<script src="/assets/painel/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="/assets/painel/js/bootstrap-notify.js"></script>

<!-- Sweet Alert 2 plugin -->
<script src="/assets/painel/js/sweetalert2.js"></script>

<!-- Vector Map plugin -->
<script src="/assets/painel/js/jquery-jvectormap.js"></script>

<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js"></script>

<!-- Wizard Plugin    -->
<script src="/assets/painel/js/jquery.bootstrap.wizard.min.js"></script>

<!--  Datatable Plugin    -->
<script src="/assets/painel/js/bootstrap-table.js"></script>

<!--  Full Calendar Plugin    -->
<script src="/assets/painel/js/fullcalendar.min.js"></script>

<!-- Light Bootstrap Dashboard Core javascript and methods -->
<script src="/assets/painel/js/light-bootstrap-dashboard.js"></script>

<!--   Sharrre Library    -->
<script src="/assets/painel/js/jquery.sharrre.js"></script>

<!-- Light Bootstrap Dashboard DEMO methods, don't include it in your project! -->
<script src="/assets/painel/js/demo.js"></script>

<!--  Ckeditor -->
<script src="/assets/painel/js/ckeditor/ckeditor.js"></script>

<script type="text/javascript">
    $().ready(function(){
        lbd.checkFullPageBackgroundImage();

        setTimeout(function(){
            // after 1000 ms we add the class animated to the login/register card
            $('.card').removeClass('card-hidden');
        }, 700)
    });
</script>



</html>
	    
