<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                   <?php if(empty($this->id)):?>
                        <div class="header">Novo</div>
                    <?php else:?>
                        <div class="header">Editar</div>
                    <?php endif; ?>
                   <div class="content">
                        <form method="post" enctype="multipart/form-data" action="/<?php echo $this->layout()->routes['module'];?>/<?php echo $this->layout()->routes['controller'];?>/save">
                           <input type="hidden" name="id_depoimento" value="<?php echo $this->post->id_depoimento;?>" />
                           <div class="row">
                               <div class="col-md-12">
                                   <div class="form-group">
                                       <label>ORDEM</label>
                                       <input type="text " class="form-control inteiro" name="ordem" value="<?php echo $this->post->ordem; ?>" />
                                   </div>
                                   <div class="form-group">
                                       <label>STATUS</label>
                                       <select name="status" class="form-control">
                                           <option <?php if($this->post->status == 'ativo'){ echo 'selected="selected"';} ?> value="ativo">ATIVO</option>
                                           <option <?php if($this->post->status == 'inativo'){ echo 'selected="selected"';} ?> value="inativo">INATIVO</option>
                                       </select>
                                   </div>
                                   <div class="form-group">
                                       <label>NOME</label>
                                       <input type="text" name="nome" required="required"  class="form-control " value="<?php echo $this->post->nome;?>" />
                                   </div>
                                   <div class="form-group">
                                       <label>CARGO</label>
                                       <input type="text" name="cargo" required="required"  class="form-control " value="<?php echo $this->post->cargo;?>" />
                                   </div>
                                   <div class="form-group">
                                       <label>TEXTO</label>
                                       <textarea name="texto" required="required" class="form-control"><?php echo $this->post->texto?></textarea>
                                   </div>
                                   <div class="form-group">
                                       <label>FOTO</label>
                                       <input type="file" name="foto" class="form-control " value="" />
                                   </div>
                                   <?php if(!empty($this->post->foto)):?>
                                   <div class="form-group">
                                       <label>FOTO ATUAL</label>
                                       <img width="100" src="/assets/uploads/depoimentos/<?php echo $this->post->foto;?>" alt=""/>
                                   </div>
                                   <?php endif;?>
                                  <button type="submit" class="btn btn-fill btn-info">Salvar</button>
                                </div>
                            </div>
                        </form>
                   </div>
               </div>
            </div>
        </div>
    </div>
</div>

