<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/equipamentos/index">
        <i class="fas fa-newspaper"></i>
        <p>Noticias</p>
    </a>
</li>
<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/equipamentos/index">
        <i class="fas fa-cogs"></i>
        <p>Equipamentos</p>
    </a>
</li>
<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/banners/index">
        <i class="far fa-image"></i>
        <p>Banners</p>
    </a>
</li>

<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/banners/index">
        <i class="far fa-file-excel"></i>
        <p>Repositórios</p>
    </a>
</li>

<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/banners/index">
        <i class="far fa-lightbulb"></i>
        <p>Soluções</p>
    </a>
</li>
<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/depoimentos/index">
        <i class="far fa-comments"></i>
        <p>Depoimentos</p>
    </a>
</li>
<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/trabalhe-conosco/index">
        <i class="fas fa-briefcase"></i>
        <p>Trabalhe Conosco</p>
    </a>
</li>
<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/contatos/index">
        <i class="fas fa-envelope"></i>
        <p>Contatos</p>
    </a>
</li>
<li>
    <a href="/<?php echo $this->layout()->routes['module']?>/newsletter/index">
        <i class="far fa-newspaper"></i>
        <p>Newsletter</p>
    </a>
</li>



